### ISSUE TITLE
Minimized window dimensions not restored

### ISSUE THREAD

**Issue by ouroborus** [gurrhack/RestoreWindows#1]
If a window is minimized when the system sleeps the monitor, the dimensions are not recovered on those minimized windows and are essentially lost. This happens even if the timer is set such that the restore happens well after the monitor has finished awakening.

**Comment by gurrhack** [comment]
I can reproduce that, but only for windows that are maximized first and then minimized. Do you have the same bug for windows that were not previously maximized?

**Comment by ouroborus** [comment]
For me the steps are:
1. Open a new window and resize as needed
2. Minimize window
3. Turn off monitor, wait, turn on monitor
4. Restore window

I have the timer set to 7000 and I'm on Windows 7. 7000 is enough that the monitor completely recovers before RestoreWindows restores things so I can see it when it happens. Seems like something is happening with the minified windows as the "minify window" animation is visible when it kicks in.

**Comment by gurrhack** [comment]
Try it now

**Comment by ouroborus** [comment]
Excellent, works on both maximized and minimized windows now.
