### ISSUE TITLE
restoring windows 200 ish pixels down

### ISSUE THREAD

**Issue by ghost** [gurrhack/RestoreWindows#2]
hey gurrhack. thank for your work on this app.

4k monitor. 100% scaling. windows 10 build 10240.
i have the windows taskbar at the top.
anyway window touching the top is restored to the correct positition but about 200 [very rough guess] pixels vertically down. same horizontal position.

apps launches on windows startup. no settings changed.
appreciate your time and effort.
gerry

**Comment by gurrhack** [comment]
Probably because it assumes the taskbar is at the bottom. I'll take a look at it
