### ISSUE TITLE
Intermittent crash

### ISSUE THREAD

**Issue by sbs20** [gurrhack/RestoreWindows#5]
https://github.com/gurrhack/RestoreWindows/blob/949ad835718ba7f223eb3b8fada9466184c21473/RestoreWindows/Main.cpp#L57

Observed occasional crash when I'd watched an Amazon video, fullscreen in MS Edge. Couldn't reproduce on development machine. After some binary chop trial and error I found that it wouldn't crash if I commented out this line (and the ones after).

Then found [this](https://developercommunity.visualstudio.com/content/problem/35105/-vsnprintf-s-cases-program-to-crash.html)

Changing the third parameter from `buf.size()` to `len` worked for me

	len = _vsnprintf_s(buf.data(), buf.size(), len, fmt, args);

I would do a pull request, but my fork of the project is all over the garage floor at the moment.

I hope that helps,

Sam

**Comment by gurrhack** [comment]
Thanks for finding that! I'll push your fix shortly.
